substitutions:
  device_name: bluetooth-proxy-hub
  api_url: !secret update_url
  friendly_name: BLE Gateway
  

esphome:
  name: ${device_name}
  #name_add_mac_suffix: true
  friendly_name: "${friendly_name}"
  project:
    name: Bibliotehnika.blegtw
    version: "2024.10.3"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_iot
  password: !secret wifi_pass
  # Optional manual IP
  manual_ip:
    static_ip: !secret bluetooth-proxy-hub_ip
    gateway: !secret gateway
    subnet: 255.255.0.0
    dns1: !secret dns1
#    dns2: !secret dns2
  fast_connect: true

  ap:
    ssid: "${device_name}"
    password: !secret wifi_pass

captive_portal:

api:

mqtt:
  broker: !secret broker_ip
  port: 1883
  id: rf_mqtt
  username: esphome
  password: !secret mqtt_password
  discovery: false
# ...Status
  birth_message:
    topic: esphome/${device_name}/status
    payload: online
  will_message:
    topic: esphome/${device_name}/status
    payload: offline

logger:

http_request:
  #verify_ssl: false
  # id: http_client

ota:
  - platform: esphome
    password: !secret remote_pass
  - platform: http_request

update:
  - platform: http_request
    name: Firmware Update
    source: ${api_url}   

improv_serial:

dashboard_import:
  package_import_url: !secret package_url

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: template
    name: "Update"
    id: firmware_update
    on_press:
      then:
        - ota.http_request.flash:
            md5_url: https://github.com/tominik83/bluetooth-proxy-hub/raw/refs/heads/main/firmware.md5
            url: https://github.com/tominik83/bluetooth-proxy-hub/raw/refs/heads/main/firmware.ota.bin
            username: !secret web_user
            password: !secret web_pass
        - logger.log: "This message should not be displayed because the device reboots"
    entity_category: diagnostic

  
  - platform: shutdown
    name: "${friendly_name} Shutdown"
    entity_category: diagnostic

  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: diagnostic

  - platform: safe_mode
    name: "${friendly_name} Restart (Safe Mode)"
    entity_category: diagnostic
