substitutions:
  name: bluetooth-proxy-hub
  api_url: !secret update_url
  friendly_name: BLE Gateway
  board: esp32dev

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: "${friendly_name}"
  project:
    name: bbt.blegtw
    version: "2024.10.3"

esp32:
  board: ${board}
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_iot
  password: !secret wifi_pass
  # Optional manual IP
  manual_ip:
    static_ip: !secret bluetooth-proxy-hub_ip
    gateway: !secret gateway
    subnet: 255.255.0.0
    dns1: !secret dns1
#    dns2: !secret dns2
  fast_connect: true

  ap:
    ssid: "bluetooth-proxy-hub"
    password: !secret wifi_pass

captive_portal:

api:

# mqtt:
#   broker: !secret broker_ip
#   port: 1883
#   id: rf_mqtt
#   username: esphome
#   password: !secret mqtt_password
# # ...Status
#   birth_message:
#     topic: esphome/${name}/status
#     payload: online
#   will_message:
#     topic: esphome/${name}/status
#     payload: offline

logger:

http_request:
  #verify_ssl: false
  # id: http_client

ota:
  - platform: esphome
    #password: !secret remote_pass
  - platform: http_request
    

improv_serial:

#dashboard_import:
#  package_import_url: github://esphome/bluetooth-proxies/esp32-generic.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: template
    name: "Update"
    id: firmware_update
    on_press:
      then:
        - ota.http_request.flash:
            md5_url: https://github.com/tominik83/${name}/raw/refs/heads/main/firmware.md5
            url: https://github.com/tominik83/${name}/raw/refs/heads/main/firmware.ota.bin
            username: !secret web_user
            password: !secret web_pass
        - logger.log: "This message should not be displayed because the device reboots"


  
  - platform: shutdown
    name: "${friendly_name} Shutdown"
    entity_category: diagnostic

  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: diagnostic

  - platform: safe_mode
    name: "${friendly_name} Restart (Safe Mode)"
    entity_category: diagnostic